### 20MAI0050 - Nancy Pal
https://github.com/nancypal50/DL_LAB/tree/main/ASSI5

## Implementing RNN using keras for Text Generation.

In [35]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import np_utils

In [36]:
data = open("input_file.txt").read().lower()


In [37]:
chars = sorted(list(set(data)))
chars

['\n',
 ' ',
 "'",
 ',',
 '-',
 '.',
 ';',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'y']

In [38]:
totalChars = len(data)
totalChars

1860

In [39]:
numberOfUniqueChars = len(chars)
numberOfUniqueChars

30

In [40]:
CharsForids = {char:Id for Id, char in enumerate(chars)}
CharsForids

{'\n': 0,
 ' ': 1,
 "'": 2,
 ',': 3,
 '-': 4,
 '.': 5,
 ';': 6,
 'a': 7,
 'b': 8,
 'c': 9,
 'd': 10,
 'e': 11,
 'f': 12,
 'g': 13,
 'h': 14,
 'i': 15,
 'k': 16,
 'l': 17,
 'm': 18,
 'n': 19,
 'o': 20,
 'p': 21,
 'q': 22,
 'r': 23,
 's': 24,
 't': 25,
 'u': 26,
 'v': 27,
 'w': 28,
 'y': 29}

In [41]:
idsForChars = {Id:char for Id, char in enumerate(chars)}
idsForChars

{0: '\n',
 1: ' ',
 2: "'",
 3: ',',
 4: '-',
 5: '.',
 6: ';',
 7: 'a',
 8: 'b',
 9: 'c',
 10: 'd',
 11: 'e',
 12: 'f',
 13: 'g',
 14: 'h',
 15: 'i',
 16: 'k',
 17: 'l',
 18: 'm',
 19: 'n',
 20: 'o',
 21: 'p',
 22: 'q',
 23: 'r',
 24: 's',
 25: 't',
 26: 'u',
 27: 'v',
 28: 'w',
 29: 'y'}

In [42]:
numberOfCharsToLearn = 100

In [43]:
CharsForids["o"]

20

In [44]:
charX = []
y = []

In [45]:

counter = totalChars - numberOfCharsToLearn
for i in range(0, counter, 1):
  
  theInputChars = data[i:i+numberOfCharsToLearn]
  
  theOutputChars = data[i + numberOfCharsToLearn]
  
  charX.append([CharsForids[char] for char in theInputChars])
 
  y.append(CharsForids[theOutputChars])

#To convert data into right format which can be fed to RNN


In [46]:
X = np.reshape(charX, (len(charX), numberOfCharsToLearn, 1))


In [47]:
X = X/float(numberOfUniqueChars)
y = np_utils.to_categorical(y)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#Building RNN Model

In [48]:
 model = Sequential()


In [49]:
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))


In [50]:
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(X, y, epochs=50, batch_size=128)
model.save_weights("Othello.hdf5")


Epoch 1/50
14/14 [==============================] - 2s 22ms/step - loss: 3.2764
Epoch 2/50
14/14 [==============================] - 0s 21ms/step - loss: 3.0094
Epoch 3/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9824
Epoch 4/50
14/14 [==============================] - 0s 21ms/step - loss: 2.9896
Epoch 5/50
14/14 [==============================] - 0s 20ms/step - loss: 3.0184
Epoch 6/50
14/14 [==============================] - 0s 20ms/step - loss: 3.0109
Epoch 7/50
14/14 [==============================] - 0s 20ms/step - loss: 3.0050
Epoch 8/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9855
Epoch 9/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9962
Epoch 10/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9975
Epoch 11/50
14/14 [==============================] - 0s 20ms/step - loss: 2.9603
Epoch 12/50
14/14 [==============================] - 0s 21ms/step - loss: 2.9644
Epoch 13/50
14/14 [==================

#Code to generate new text

In [57]:
for i in range(500):
  randomVal = np.random.randint(0, len(charX)-1)
  randomStart = charX[randomVal]

  x = np.reshape(randomStart, (1, len(randomStart), 1))
  x = x/float(numberOfUniqueChars)
  pred = model.predict(x)
  index = np.argmax(pred)
  randomStart.append(index)
  randomStart = randomStart[1: len(randomStart)]

#So our newly generated text is:




In [58]:
print("".join([idsForChars[value] for value in randomStart]))

hence;
which ever she could with haste dispatch,
she'd come again, and with a greedy ear
devour up th
